[book]
authors = ["Kadoi Takemaru"]
language = "ja"
multilingual = true
src = "src"
title = "how2makePC"
description = "make a computer"

[build]
build-dir = "docs"

[output.html]
mathjax-support = true